### ISSUE TITLE
Login + Logout

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#1]
- [x] logout dialog
- [x] LOGIN USED IDENTITY WITHOUT EMAIL
- [x] indicate that user has registered/logged in using one of the IdPs
- [x] add [login without using runtime admin gui](https://github.com/reTHINK-project/dev-runtime-browser/issues/99)

- [x] add logout to runtimeUA (https://github.com/reTHINK-project/dev-runtime-core/issues/257) and runtimeUAStub (https://github.com/reTHINK-project/dev-runtime-browser/issues/98)  

- [x] ["hide" rethink elements from DOM](https://github.com/reTHINK-project/dev-runtime-browser/issues/100)

- [x] iDs.defaultIdentity.value used as userID (`user://<idp-domain>/<identifier>`)

**Comment by Felgueiras** [comment]
login with Goggle is functional, still have to "hide" rethink elements from DOM

**Comment by Felgueiras** [comment]
need to push updates to runtime-browser, concerning messaging between App document and runtime-browser document

**Comment by Felgueiras** [comment]
add logout in runtimeUA that will ask IDM to make a reset: currentIdentity and defaultIdentity become empty, which corresponds to not having chosen any identity

https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/runtime/RuntimeUA.js#L435
