### ISSUE TITLE
iOS integration

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-dsm-app#121]
**Links**:
- https://medium.com/@firt/pwas-are-coming-to-ios-11-3-cupertino-we-have-a-problem-2ff49fd7d6ea
- https://medium.com/@nikoloza/how-to-debug-remote-ios-device-using-chrome-devtools-f44d697003a7
- https://github.com/google/ios-webkit-debug-proxy
- https://developer.telerik.com/featured/a-concise-guide-to-remote-debugging-on-ios-android-and-windows-phone/#weinre
- https://people.apache.org/~pmuellr/weinre/docs/latest/Home.html

**[Limitations compared with native iOS apps](https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7):**
- The app can store offline data and files only up to 50 Mb
- If the user doesn’t use the app for a few weeks, iOS will free up the app’s files. The icon will still be there on the home screen, and when accessed the app will be downloaded again
- No access to some features, such as Bluetooth, serial, Beacons, Touch ID, Face ID, ARKit, altimeter sensor, battery information
- No access to execute code while in the background
- No access to private information (contacts, background location) and also no access to native social apps
- No Push Notifications, no icon badge or Siri integration
- [No install banners](https://user-images.githubusercontent.com/7281851/47645581-54780180-db69-11e8-934d-e1a69fb8807f.png)
- Additional pseudo-browsers available in the App Store, such as Chrome, Firefox, Brave or Edge won’t be able to install a PWA or use Service Workers.

**TODO [link1](https://medium.com/appscope/designing-native-like-progressive-web-apps-for-ios-1b3cdda1d0e8) [link2](https://www.netguru.co/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native):**
- [x]  Make it standalone
- [x]  Add a custom icon
- [ ]  Add a [custom splash screen](https://appsco.pe/developer/splash-screens)
- [x]  Change the status bar
- [x]  Give it a short name
- [x]  Disable selection, highlighting, and callouts
- [ ]  Enable tap effects
- [ ] Explain install process (?)

**Comment by Felgueiras** [comment]
disable 'allow notifications dialog' (https://github.com/reTHINK-project/dev-dsm-app/blob/develop/src/scenes/Dashboard/Dashboard.js#L47)
