### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-dsm-app#34]
[Docker hub](https://hub.docker.com/r/rethinkaltice/dev-push-server/)

**Resources:**
- https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications
- https://developers.google.com/web/ilt/pwa/lab-integrating-web-push

**TODO:**
- [ ] cancel subscription (on server)
- [x] open app, not browser
- [x] store notification from SW
- [x] SW error
- [x] ask for permission after first points won/points threshold
- [x] mockup
- [x] server implementation
- [x] number of new notifications in UI
- [x] cancel notifications from settings

**Use cases:**
- link pra inquérito
- campanha
- novo bónus
- novo quiz
